export const MOCK_TOURNAMENTS = [
  {
    id: "t1",
    title: "Free Fire Grand Series",
    game: "Free Fire",
    game_mode: "Squad",
    entry_fee: 50,
    prize_pool: 50000,
    max_slots: 25,
    filled_slots: 18,
    match_time: new Date(Date.now() + 2 * 3600000).toISOString(),
    map_name: "Bermuda",
    status: "upcoming",
    banner_url: null,
    rules: "Standard tournament rules apply. No hacking or cheating. Results are final.",
  },
  {
    id: "t2",
    title: "BGMI Pro League",
    game: "BGMI",
    game_mode: "Solo",
    entry_fee: 100,
    prize_pool: 100000,
    max_slots: 100,
    filled_slots: 100,
    match_time: new Date(Date.now() + 30 * 60000).toISOString(),
    map_name: "Erangel",
    status: "live",
    banner_url: null,
    rules: "Top 3 places rewarded. Kills count as tiebreaker.",
  },
  {
    id: "t3",
    title: "Valorant Ranked Cup",
    game: "Valorant",
    game_mode: "Squad",
    entry_fee: 200,
    prize_pool: 250000,
    max_slots: 16,
    filled_slots: 12,
    match_time: new Date(Date.now() + 6 * 3600000).toISOString(),
    map_name: "Ascent",
    status: "upcoming",
    banner_url: null,
    rules: "5v5 elimination format. Best of 3.",
  },
  {
    id: "t4",
    title: "COD Mobile Mayhem",
    game: "COD Mobile",
    game_mode: "Duo",
    entry_fee: 75,
    prize_pool: 75000,
    max_slots: 50,
    filled_slots: 31,
    match_time: new Date(Date.now() + 4 * 3600000).toISOString(),
    map_name: "Nuketown",
    status: "upcoming",
    banner_url: null,
    rules: "2v2 format. Hardpoint mode.",
  },
  {
    id: "t5",
    title: "PUBG Mobile Elite",
    game: "PUBG Mobile",
    game_mode: "Squad",
    entry_fee: 150,
    prize_pool: 200000,
    max_slots: 25,
    filled_slots: 25,
    match_time: new Date(Date.now() - 3600000).toISOString(),
    map_name: "Miramar",
    status: "completed",
    banner_url: null,
    rules: "Points based system. Top 10 receive prizes.",
  },
  {
    id: "t6",
    title: "Free Fire Solo Blitz",
    game: "Free Fire",
    game_mode: "Solo",
    entry_fee: 30,
    prize_pool: 25000,
    max_slots: 48,
    filled_slots: 22,
    match_time: new Date(Date.now() + 12 * 3600000).toISOString(),
    map_name: "Purgatory",
    status: "upcoming",
    banner_url: null,
    rules: "Solo survival. Most kills win.",
  },
];

export const MOCK_LEADERBOARD = [
  { rank: 1, username: "NightShade_X", game: "BGMI", wins: 47, kills: 2840, earnings: 185000, avatar: null, trend: "up" },
  { rank: 2, username: "ShadowKing99", game: "Free Fire", wins: 42, kills: 2210, earnings: 162000, avatar: null, trend: "up" },
  { rank: 3, username: "ProSniper_Z", game: "Valorant", wins: 38, kills: 1890, earnings: 143000, avatar: null, trend: "down" },
  { rank: 4, username: "EliteForce77", game: "BGMI", wins: 35, kills: 1740, earnings: 128500, avatar: null, trend: "up" },
  { rank: 5, username: "GhostRider_M", game: "COD Mobile", wins: 31, kills: 1620, earnings: 115000, avatar: null, trend: "same" },
  { rank: 6, username: "ThunderBolt_S", game: "Free Fire", wins: 28, kills: 1510, earnings: 98000, avatar: null, trend: "down" },
  { rank: 7, username: "NeonAssassin", game: "PUBG Mobile", wins: 26, kills: 1440, earnings: 87500, avatar: null, trend: "up" },
  { rank: 8, username: "RedViper_99", game: "Valorant", wins: 24, kills: 1380, earnings: 76000, avatar: null, trend: "up" },
  { rank: 9, username: "CyberHawk_V2", game: "BGMI", wins: 22, kills: 1290, earnings: 65000, avatar: null, trend: "down" },
  { rank: 10, username: "StormRaider_K", game: "Free Fire", wins: 20, kills: 1200, earnings: 54500, avatar: null, trend: "same" },
];

export const MOCK_RECENT_WINNERS = [
  { username: "NightShade_X", tournament: "BGMI Pro League", prize: 50000, position: 1, game: "BGMI" },
  { username: "ShadowKing99", tournament: "Free Fire Grand Series", prize: 25000, position: 1, game: "Free Fire" },
  { username: "ProSniper_Z", tournament: "Valorant Ranked Cup", prize: 75000, position: 1, game: "Valorant" },
  { username: "EliteForce77", tournament: "COD Mobile Mayhem", prize: 30000, position: 1, game: "COD Mobile" },
];

export const MOCK_STATS = {
  totalPlayers: 142580,
  totalPrizePool: 12500000,
  tournamentsThisMonth: 284,
  activeTournaments: 7,
};

export const MOCK_USER = {
  id: "demo-user",
  username: "DemoPlayer",
  game_id: "FF123456789",
  wallet_balance: 1250,
  total_winnings: 8500,
  kills: 342,
  rank_points: 4820,
  rank: "Gold",
  tournaments_played: 18,
  tournaments_won: 3,
};

export const MOCK_NOTIFICATIONS = [
  { id: "n1", title: "Room ID Released", message: "Room ID for BGMI Pro League is now available!", read: false, created_at: new Date(Date.now() - 300000).toISOString() },
  { id: "n2", title: "Payment Approved", message: "Your ₹100 deposit has been approved.", read: false, created_at: new Date(Date.now() - 3600000).toISOString() },
  { id: "n3", title: "Match Result", message: "You finished 3rd in Free Fire Solo Blitz! ₹500 credited.", read: true, created_at: new Date(Date.now() - 86400000).toISOString() },
];

export const MOCK_TRANSACTIONS = [
  { id: "tx1", type: "deposit", amount: 500, status: "completed", created_at: new Date(Date.now() - 2 * 86400000).toISOString() },
  { id: "tx2", type: "entry_fee", amount: -50, status: "completed", created_at: new Date(Date.now() - 86400000).toISOString() },
  { id: "tx3", type: "winning", amount: 1500, status: "completed", created_at: new Date(Date.now() - 43200000).toISOString() },
  { id: "tx4", type: "entry_fee", amount: -100, status: "completed", created_at: new Date(Date.now() - 21600000).toISOString() },
];
